Repository HSU-Likelion12-yourSide/YourSide-Server, pull requests merged in 2024-05, with the labels that each got.

#7 ✨ Test
  README.md
  erd.png
Labels: 👋🏻혜진, ✨Feat

#13 ERD 기반 Entity 생성 및 Table 조회
  yourside/src/main/java/com/likelion/yourside/YoursideApplication.java
  yourside/src/main/java/com/likelion/yourside/domain/Bookmark.java
  yourside/src/main/java/com/likelion/yourside/domain/Comment.java
  yourside/src/main/java/com/likelion/yourside/domain/Information.java
  yourside/src/main/java/com/likelion/yourside/domain/Likes.java
  yourside/src/main/java/com/likelion/yourside/domain/Post.java
  yourside/src/main/java/com/likelion/yourside/domain/User.java
  yourside/src/main/java/com/likelion/yourside/domain/Worksheet.java
  yourside/src/main/java/com/likelion/yourside/util/entity/BaseEntity.java
Labels: 💤현승, ⚙️ Setting

#40 📝 공지사항 더미데이터 추가
  yourside/src/main/java/com/likelion/yourside/notation/controller/NotationController.java
Labels: 🌈혜진, 📄 Docs

#53 [ 마이페이지 ] 유저 정보 조회 & 노무사 인증 API
  yourside/src/main/java/com/likelion/yourside/domain/User.java
  yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
  yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetuserinfoResponseDto.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
  yourside/src/main/java/com/likelion/yourside/posting/repository/PostingRepository.java
  yourside/src/main/java/com/likelion/yourside/worksheet/repository/WorksheetRepository.java
Labels: 💤현승, ✨Feat

#57 [ 마이 페이지 ] 내 근로 결과지 조회 API 구현
  yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
  yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetworksheetlistResponseDto.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
  yourside/src/main/java/com/likelion/yourside/util/entity/BaseEntity.java
  yourside/src/main/java/com/likelion/yourside/worksheet/repository/WorksheetRepository.java
Labels: 💤현승, ✨Feat

#66 [ 마이 페이지 ] 내 질문 리스트 조회 API 구현
  yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
  yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetpostinglistResponseDto.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
Labels: 💤현승, ✨Feat

#72 [ 마이 페이지 ] 내 책갈피 조회 리스트 API 구현
  yourside/src/main/java/com/likelion/yourside/bookmark/repository/BookmarkRepository.java
  yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
Labels: 💤현승, ✨Feat

#75 [ 마이 페이지 ] CommentCount 수정 & 내 답변 리스트 조회 API 구현
  yourside/src/main/java/com/likelion/yourside/comment/repository/CommentRepository.java
  yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
  yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetcommentlistResponseDto.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
  yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
Labels: 💤현승, 🚨 Fix

#84 ✨ 인기 게시글 조회 API 구현 & Entity field 추가 & 게시글 등록 수정(type 추가)
  before switching branches
  yourside/src/main/java/com/likelion/yourside/domain/Comment.java
  yourside/src/main/java/com/likelion/yourside/domain/Dislikes.java
  yourside/src/main/java/com/likelion/yourside/domain/Posting.java
  yourside/src/main/java/com/likelion/yourside/domain/User.java
  yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
  yourside/src/main/java/com/likelion/yourside/posting/dto/PostingCreateResponseDto.java
  yourside/src/main/java/com/likelion/yourside/posting/dto/PostingPopularListDto.java
  yourside/src/main/java/com/likelion/yourside/posting/repository/PostingRepository.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java
Labels: 🌈혜진, ✨Feat

#85 ✨ 게시글 세부 조회 API 개발
  yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
  yourside/src/main/java/com/likelion/yourside/posting/dto/PostingSearchResponseDto.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java
Labels: 🌈혜진, ✨Feat

#89 ✨ 댓글 싫어요 추가 API 개발 & 댓글 작성 부분 수정
  yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentDislikeDto.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
  yourside/src/main/java/com/likelion/yourside/dislikes/DislikesRepository.java
  yourside/src/main/java/com/likelion/yourside/domain/Comment.java
Labels: 🌈혜진, ✨Feat

#91 ✨ 댓글 싫어요 삭제 API 개발
  yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
  yourside/src/main/java/com/likelion/yourside/dislikes/DislikesRepository.java
Labels: 🌈혜진, ✨Feat

#92 [ 네편 현답 ] 댓글 좋아요/싫어요 관련 API 수정
  yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentDislikeDto.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentLikeDto.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
Labels: 🌈혜진, 🚨 Fix

#93 [ 네편 현답 ] 댓글 삭제 & 회원 강등 관련 API 구현
  .idea/workspace.xml
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
  yourside/src/main/java/com/likelion/yourside/domain/Comment.java
  yourside/src/main/java/com/likelion/yourside/domain/User.java
Labels: 🌈혜진, ✨Feat, 🚨 Fix

#102 🩹 Fix calculate Logic
  yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java
Labels: 💤현승, 🚨 Fix

#109 ✏️ [ 네편 현답 ] 게시글 조회 - 게시글 타입 필터 추가
  .idea/workspace.xml
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
  yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
  yourside/src/main/java/com/likelion/yourside/posting/repository/PostingRepository.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java
Labels: ✨Feat, 🚨 Fix

#111 ✏️ Comment 댓글 전체 조회 관련 수정
  .idea/workspace.xml
  yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListRequestDto.java
  yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListResponseDto.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
Labels: 🌈혜진, 🚨 Fix

#115 🩹 Fix tier
  yourside/src/main/java/com/likelion/yourside/domain/User.java
Labels: 💤현승, 🚨 Fix

#120 ✨ [ 네편 현답 ] 댓글 작성 시 해당 User가 없는 경우에 대한 예외처리 추가
  .idea/workspace.xml
  yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
Labels: 🌈혜진, ✨Feat

#124 ✨ 게시글 추가 - 근로결과지 선택하지 않은 경우에 대한 예외처리 추가
  .idea/workspace.xml
  yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java
Labels: 🌈혜진, ✨Feat
